### ISSUE TITLE
Issue-feat: add get companies method

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#107]
Automated Review Comments
Issues in src/app/services/company.service.ts:
  - (6, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (42, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
