### ISSUE TITLE
Issue-Merge pull request #6 from Crypto-Vitae/contracts

Contracts

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#115]
Automated Review Comments
Issues in src/app/auth/company/companies/companies.component.html:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
Issues in src/app/auth/company/companies/companies.component.ts:
  - (8, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in src/app/services/company.service.ts:
  - (6, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in src/assets/abis/CryptoVitaeCompanyNFT.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (528, 'Hardcoded string found')
  - (531, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (558, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (582, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (605, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (615, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (627, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (637, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (648, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (660, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (672, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (680, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (700, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (707, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (710, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (716, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (720, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (725, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (733, 'Hardcoded string found')
  - (734, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (739, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (741, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (752, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (757, 'Hardcoded string found')
  - (758, 'Hardcoded string found')
  - (759, 'Hardcoded string found')
  - (760, 'Hardcoded string found')
  - (763, 'Hardcoded string found')
  - (764, 'Hardcoded string found')
  - (765, 'Hardcoded string found')
  - (766, 'Hardcoded string found')
  - (769, 'Hardcoded string found')
  - (770, 'Hardcoded string found')
  - (773, 'Hardcoded string found')
  - (775, 'Hardcoded string found')
  - (776, 'Hardcoded string found')
  - (777, 'Hardcoded string found')
  - (780, 'Hardcoded string found')
  - (781, 'Hardcoded string found')
  - (782, 'Hardcoded string found')
  - (785, 'Hardcoded string found')
  - (786, 'Hardcoded string found')
  - (787, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (791, 'Hardcoded string found')
  - (793, 'Hardcoded string found')
  - (794, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (798, 'Hardcoded string found')
  - (799, 'Hardcoded string found')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (806, 'Hardcoded string found')
  - (807, 'Hardcoded string found')
  - (810, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (817, 'Hardcoded string found')
  - (818, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (821, 'Hardcoded string found')
  - (822, 'Hardcoded string found')
  - (825, 'Hardcoded string found')
  - (826, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (832, 'Hardcoded string found')
  - (833, 'Hardcoded string found')
  - (836, 'Hardcoded string found')
  - (837, 'Hardcoded string found')
  - (839, 'Hardcoded string found')
  - (840, 'Hardcoded string found')
  - (841, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (845, 'Hardcoded string found')
  - (848, 'Hardcoded string found')
  - (850, 'Hardcoded string found')
  - (851, 'Hardcoded string found')
  - (852, 'Hardcoded string found')
  - (855, 'Hardcoded string found')
  - (856, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (861, 'Hardcoded string found')
  - (863, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (865, 'Hardcoded string found')
  - (868, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (872, 'Hardcoded string found')
  - (873, 'Hardcoded string found')
  - (874, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (878, 'Hardcoded string found')
  - (881, 'Hardcoded string found')
  - (882, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (886, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (889, 'Hardcoded string found')
  - (890, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (905, 'Hardcoded string found')
  - (906, 'Hardcoded string found')
  - (908, 'Hardcoded string found')
  - (909, 'Hardcoded string found')
  - (910, 'Hardcoded string found')
  - (913, 'Hardcoded string found')
  - (914, 'Hardcoded string found')
  - (917, 'Hardcoded string found')
  - (918, 'Hardcoded string found')
  - (919, 'Hardcoded string found')
  - (920, 'Hardcoded string found')
  - (921, 'Hardcoded string found')
  - (924, 'Hardcoded string found')
  - (926, 'Hardcoded string found')
  - (927, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (931, 'Hardcoded string found')
  - (932, 'Hardcoded string found')
  - (933, 'Hardcoded string found')
  - (936, 'Hardcoded string found')
  - (937, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (941, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
  - (943, 'Hardcoded string found')
  - (944, 'Hardcoded string found')
  - (947, 'Hardcoded string found')
  - (949, 'Hardcoded string found')
  - (950, 'Hardcoded string found')
  - (951, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (955, 'Hardcoded string found')
  - (956, 'Hardcoded string found')
  - (959, 'Hardcoded string found')
  - (960, 'Hardcoded string found')
  - (961, 'Hardcoded string found')
  - (964, 'Hardcoded string found')
  - (965, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (969, 'Hardcoded string found')
  - (970, 'Hardcoded string found')
  - (971, 'Hardcoded string found')
  - (972, 'Hardcoded string found')
  - (975, 'Hardcoded string found')
  - (977, 'Hardcoded string found')
  - (978, 'Hardcoded string found')
  - (979, 'Hardcoded string found')
  - (982, 'Hardcoded string found')
  - (983, 'Hardcoded string found')
  - (984, 'Hardcoded string found')
  - (987, 'Hardcoded string found')
  - (988, 'Hardcoded string found')
  - (989, 'Hardcoded string found')
  - (990, 'Hardcoded string found')
  - (993, 'Hardcoded string found')
  - (995, 'Hardcoded string found')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (1000, 'Hardcoded string found')
  - (1001, 'Hardcoded string found')
  - (1003, 'Hardcoded string found')
  - (1004, 'Hardcoded string found')
  - (1005, 'Hardcoded string found')
  - (1008, 'Hardcoded string found')
  - (1009, 'Hardcoded string found')
  - (1012, 'Hardcoded string found')
  - (1013, 'Hardcoded string found')
  - (1014, 'Hardcoded string found')
  - (1016, 'Hardcoded string found')
  - (1017, 'Hardcoded string found')
  - (1018, 'Hardcoded string found')
  - (1021, 'Hardcoded string found')
  - (1022, 'Hardcoded string found')
  - (1025, 'Hardcoded string found')
  - (1026, 'Hardcoded string found')
  - (1027, 'Hardcoded string found')
  - (1029, 'Hardcoded string found')
  - (1030, 'Hardcoded string found')
  - (1031, 'Hardcoded string found')
  - (1034, 'Hardcoded string found')
  - (1035, 'Hardcoded string found')
  - (1038, 'Hardcoded string found')
  - (1040, 'Hardcoded string found')
  - (1041, 'Hardcoded string found')
  - (1042, 'Hardcoded string found')
  - (1045, 'Hardcoded string found')
  - (1046, 'Hardcoded string found')
  - (1048, 'Hardcoded string found')
  - (1049, 'Hardcoded string found')
  - (1050, 'Hardcoded string found')
  - (1053, 'Hardcoded string found')
  - (1054, 'Hardcoded string found')
  - (1057, 'Hardcoded string found')
  - (1058, 'Hardcoded string found')
  - (1059, 'Hardcoded string found')
  - (1061, 'Hardcoded string found')
  - (1062, 'Hardcoded string found')
  - (1063, 'Hardcoded string found')
  - (1066, 'Hardcoded string found')
  - (1067, 'Hardcoded string found')
  - (1070, 'Hardcoded string found')
  - (1072, 'Hardcoded string found')
  - (1073, 'Hardcoded string found')
  - (1074, 'Hardcoded string found')
  - (1077, 'Hardcoded string found')
  - (1078, 'Hardcoded string found')
  - (1079, 'Hardcoded string found')
  - (1082, 'Hardcoded string found')
  - (1083, 'Hardcoded string found')
  - (1084, 'Hardcoded string found')
  - (1087, 'Hardcoded string found')
  - (1088, 'Hardcoded string found')
  - (1089, 'Hardcoded string found')
  - (1090, 'Hardcoded string found')
  - (1093, 'Hardcoded string found')
  - (1095, 'Hardcoded string found')
  - (1096, 'Hardcoded string found')
  - (1097, 'Hardcoded string found')
  - (1100, 'Hardcoded string found')
  - (1101, 'Hardcoded string found')
  - (1102, 'Hardcoded string found')
  - (1103, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
