### ISSUE TITLE
Issue-feat: added prospectos component

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#117]
Automated Review Comments
Issues in src/app/app.routes.ts:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/app/auth/company/company-home/company-home.component.ts:
  - (2, 'Hardcoded string found')
Issues in src/app/auth/company/company-info/view-employees/view-employees.component.html:
  - (2, 'Hardcoded string found')
Issues in src/app/auth/company/view-prospectos/view-prospectos.component.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in src/app/auth/company/view-prospectos/view-prospectos.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/app/auth/company/view-prospectos/view-prospectos.component.ts:
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
