### ISSUE TITLE
Issue-add: request list component

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#12]
Automated Review Comments
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/app/auth/personal/request-list/request-list.component.html:
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in src/app/auth/personal/request-list/request-list.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/app/auth/personal/request-list/request-list.component.ts:
  - (18, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
