### ISSUE TITLE
Issue-feat: added sidebar and navbar

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#14]
Automated Review Comments
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/app/auth/personal/personal-home/personal-home.component.html:
  - (7, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
Issues in src/app/auth/personal/personal-home/personal-home.component.ts:
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in tailwind.config.js:
  - (13, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
