### ISSUE TITLE
Issue-add: company request service, confirmation component and refactor

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#22]
Automated Review Comments
Issues in angular.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in src/app/auth/company/company-home/company-home.component.html:
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
Issues in src/app/auth/company/company-home/company-home.component.ts:
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in src/app/auth/personal/personal-home/personal-home.component.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/app/auth/personal/request-confirmation/request-confirmation.component.html:
  - (14, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
Issues in src/app/auth/personal/request-confirmation/request-confirmation.component.spec.ts:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/app/auth/personal/request-confirmation/request-confirmation.component.ts:
  - (22, 'Hardcoded string found')
Issues in src/app/auth/personal/request-list/request-list.component.html:
  - (6, 'Hardcoded string found')
Issues in src/app/auth/personal/request-list/request-list.component.ts:
  - (18, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
Issues in src/app/auth/services/company-request.service.spec.ts:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/app/auth/services/company-request.service.ts:
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.css:
  - (7, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.html:
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.html:
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
