### ISSUE TITLE
Issue-chore: add metamask dependencies

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#24]
Automated Review Comments
Issues in angular.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in package.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in src/app/auth/company/company-home/company-home.component.html:
  - (7, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
Issues in src/app/auth/company/company-home/company-home.component.ts:
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in src/app/auth/personal/personal-home/personal-home.component.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.css:
  - (7, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.html:
  - (10, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.html:
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
