### ISSUE TITLE
Issue-feat: implement login with metamask

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#28]
Automated Review Comments
Issues in src/app/landing/login/login.component.ts:
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
