### ISSUE TITLE
Issue-feat(login): added dropdown for categories

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#30]
Automated Review Comments
Issues in src/app/landing/login/login.component.html:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (22, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (76, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
