### ISSUE TITLE
Issue-add: summary component, confirmed companies and refactor

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#34]
Automated Review Comments
Issues in angular.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in package.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in src/app/auth/company/company-home/company-home.component.html:
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
Issues in src/app/auth/company/company-home/company-home.component.ts:
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in src/app/auth/personal/cv-summary/cv-summary.component.html:
  - (4, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
Issues in src/app/auth/personal/cv-summary/cv-summary.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/app/auth/personal/cv-summary/cv-summary.component.ts:
  - (6, 'Line exceeds 80 characters')
Issues in src/app/auth/personal/personal-home/personal-home.component.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/app/auth/personal/request-confirmation/request-confirmation.component.html:
  - (25, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
Issues in src/app/auth/personal/request-confirmation/request-confirmation.component.ts:
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
Issues in src/app/auth/services/company-request.service.ts:
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
Issues in src/app/auth/services/request-confirmed.service.spec.ts:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/app/auth/services/request-confirmed.service.ts:
  - (6, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.css:
  - (7, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/app/landing/landing-page/landing-page.component.html:
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.html:
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
