### ISSUE TITLE
Issue-Merge branch 'main' of https://github.com/Crypto-Vitae/frontend into landing-login-page

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#45]
Automated Review Comments
Issues in angular.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/app/app.routes.ts:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in src/app/auth/personal/personal-home/personal-home.component.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (60, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
