### ISSUE TITLE
Issue-add: company info component

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#59]
Automated Review Comments
Issues in src/app/app.routes.ts:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
Issues in src/app/auth/company/companies/companies.component.html:
  - (3, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in src/app/auth/company/company-info/company-info.component.html:
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in src/app/auth/company/company-info/company-info.component.spec.ts:
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/app/landing/login/login.component.ts:
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (60, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
