### ISSUE TITLE
Issue-update: company info component

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#63]
Automated Review Comments
Issues in src/app/auth/company/companies/companies.component.html:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/app/auth/company/companies/companies.component.ts:
  - (9, 'Line exceeds 80 characters')
Issues in src/app/auth/company/company-info/company-info.component.html:
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
Issues in src/app/landing/login/login.component.ts:
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (60, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
