### ISSUE TITLE
Issue-Merge branch 'company-information' of github.com-personal:Crypto-Vitae/frontend into contracts

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#75]
Automated Review Comments
Issues in src/app/auth/company/companies/companies.component.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
Issues in src/app/auth/company/companies/companies.component.ts:
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
Issues in src/app/auth/company/company-info/company-info.component.html:
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
