### ISSUE TITLE
Issue-feat: added calendar component to add employee form

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#79]
Automated Review Comments
Issues in src/app/auth/company/company-info/company-info.component.html:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
