### ISSUE TITLE
Issue-Merge branch 'main' of github.com-personal:Crypto-Vitae/frontend into contracts

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/cryptovitae-frontend#99]
Automated Review Comments
Issues in src/app/app.routes.ts:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in src/app/auth/company/company-info/company-info.component.html:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
